name: hotel_booking_algoriza
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_rating_bar: ^4.0.1
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.0
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  image_picker:
  get:
  get_storage:
  flutter_spinkit: ^5.1.0
  cached_network_image:
  flutter_svg:
  readmore:
  flutter_localizations:
    sdk: flutter
  flutter_switch:
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lang/ar.json
    - lang/en.json
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
